# Generated by Django 2.1.1 on 2018-10-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
